[package]
name = "blindfold-exec"
description = "Isolated, sanitizing process execution runtime for Blindfold"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blindfold-core = { path = "../blindfold-core" }

[lints]
workspace = true
